import type { SbBlokData } from "@storyblok/astro";

export interface StoryblokBase extends SbBlokData {
    component: string; // The name of the component
    _uid: string; // Unique identifier for the block generated by Storyblok
    _editable: string; // Editable field for Storyblok's visual editor
}